pipeline {

    agent any

    options {
        timeout(time: 30, unit: 'MINUTES')
        disableConcurrentBuilds()
    }

    environment {
        DEBUG = 'true'
        appVersion = ''
        region = 'us-east-1'
        account_id = '736184860833'
        project = 'expense'
        environment = 'dev'
        component = 'frontend'
    }

    stages {

        stage('Read Version') {
            steps {
                script {
                    def packageJson = readJSON file: 'client/package.json'
                    env.appVersion = packageJson.version
                    echo "App Version: ${env.appVersion}"
                }
            }
        }

        stage('Install Dependencies') {
            steps {
                sh 'npm install'
            }
        }

        stage('Trivy FS Scan') {
            steps {
                sh '''
                    trivy fs \
                    --severity HIGH,CRITICAL \
                    --ignore-unfixed \
                    --exit-code 1 .
                '''
            }
        }

        stage('SonarQube Analysis') {
            environment {
                SCANNER_HOME = tool 'sonar-6.0'
            }
            steps {
                dir('.') {
                    withSonarQubeEnv('sonar-6.0') {
                        sh """
                            \$SCANNER_HOME/bin/sonar-scanner \
                            -Dsonar.projectKey=expense-frontend \
                            -Dsonar.projectName=expense-frontend \
                            -Dsonar.sources=.
                        """
                    }
                }
            }
        }

        stage('Quality Gate') {
            steps {
                timeout(time: 5, unit: 'MINUTES') {
                    waitForQualityGate abortPipeline: true
                }
            }
        }

        stage('Docker Build') {
            steps {
                withAWS(region: "${region}", credentials: 'aws-creds') {
                    sh """
                        aws ecr get-login-password --region ${region} \
                        | docker login --username AWS --password-stdin ${account_id}.dkr.ecr.${region}.amazonaws.com

                        docker build \
                        -t ${account_id}.dkr.ecr.${region}.amazonaws.com/${project}/${environment}/${component}:${appVersion} .

                        docker images
                    """
                }
            }
        }

        // stage('Trivy Image Scan') {
        //     steps {
        //         sh """
        //             trivy image \
        //             --severity HIGH,CRITICAL \
        //             --ignore-unfixed \
        //             --exit-code 1 \
        //             ${account_id}.dkr.ecr.${region}.amazonaws.com/${project}/${environment}/${component}:${appVersion}
        //         """
        //     }
        // }

        stage('Push Image To ECR') {
            steps {
                withAWS(region: "${region}", credentials: 'aws-creds') {
                    sh """
                        docker push ${account_id}.dkr.ecr.${region}.amazonaws.com/${project}/${environment}/${component}:${appVersion}
                    """
                }
            }
        }

        stage('Deploy To EKS') {
            steps {
                withAWS(region: "${region}", credentials: 'aws-creds') {
                    sh """

                        aws eks update-kubeconfig \
                        --region ${region} \
                        --name ${project}

                        kubectl get nodes

                        kubectl apply -f k8s-prod/namespace.yaml
                        kubectl apply -f k8s-prod/sc.yaml
                        kubectl apply -f k8s-prod/frontend.yaml

                        kubectl set image deployment/frontend \
                        frontend=${account_id}.dkr.ecr.${region}.amazonaws.com/${project}/${environment}/${component}:${appVersion} \
                        -n ${project}

                        kubectl rollout status deployment/frontend \
                        -n ${project} \
                        --timeout=300s

                        kubectl get pods -n ${project}
                    """
                }
            }
        }
    }

    post {
        always {
            deleteDir()
        }

        success {
            echo "Frontend pipeline completed successfully"
        }

        failure {
            echo "Frontend pipeline failed"
        }
    }
}