apiVersion: v1
kind: ConfigMap
metadata:
  name: backend
  namespace: expense
data:
  DB_HOST: mysql
---
apiVersion: v1
kind: Secret
metadata:
  name: mysql-secret
  namespace: expense
type: Opaque
data:
  DB_PWD: RXhwZW5zZUFwcEAx
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  namespace: expense
  labels:
    app: backend
    tier: api
    project: expense
spec:
  replicas: 2
  selector:
    matchLabels:
      app: backend
      tier: api
      project: expense
  template:
    metadata:
      labels:
        app: backend
        tier: api
        project: expense
    spec:
      initContainers:
      - name: wait-for-mysql
        image: busybox:1.36.1
        command:
        - sh
        - -c
        - |
          until nc -z mysql 3306; do
            echo waiting for mysql
            sleep 2
          done
      containers:
      - name: backend
        image: 736184860833.dkr.ecr.us-east-1.amazonaws.com/expense/dev/backend:1.0.0
        resources:
          limits:
            cpu: "500m"
            memory: "256Mi"
          requests:
            cpu: "100m"
            memory: "128Mi"
        envFrom:
        - configMapRef:
            name: backend
        - secretRef:
            name: mysql-secret
---
kind: Service
apiVersion: v1
metadata:
  name: backend
  namespace: expense
spec:
  selector:
    app: backend
    tier: api
    project: expense
  ports:
  - name: backend-port
    protocol: TCP
    port: 8080 # service port
    targetPort: 8080 # container port